### PR TITLE
Fixed Add-XMLItem Known Issue

### PR DESCRIPTION
**Pull request by scyellleader**
enhanced Add-XMLItem to fix multiple attributes in an element known issue. This also allows creation of first child element/attribute node

### CODE REVIEW

**Comment by scyellleader** [comment]
If this change is merged, how quickly can we have the version and DSC module in PSGallery updated?

**Comment by IngoGege** [comment]
Hi @scyellleader, first I need to test this change and update the README. I think this fix some scenarios, but not all. I think this is done within the next few days.
Thanks for helping with the module!
Ciao,
Ingo

**Comment by IngoGege** [comment]
Hi @scyellleader , this seems to be a braking change as *-TargetResource has to be modified as well. The idea is good, but I have to make sure the other functions are working properly. I'm working on it...

**Comment by scyellleader** [comment]
@IngoGege no problem.  Let me know if i can help.

**Comment by IngoGege** [comment]
@scyellleader I released version 2.0.0.1. All test were successful. Please feel free to test. If you also don't see an issue I would publish the version tomorrow.

**Comment by scyellleader** [comment]
@IngoGege the new changes are working for me.  Thanks for getting this in.  I'll close out the PR as my changes are integrated in your commits.  Thanks again!

**Pull request closed without merging**
